name: Deploy Next.js Frontend to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js (latest LTS)
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
      - name: Test SSH
        run: |
          echo "$EC2_KEY" > key.pem
          chmod 600 key.pem
          ssh -i key.pem -o StrictHostKeyChecking=no ubuntu@${EC2_HOST} "echo Connected"
        env:
          EC2_KEY: ${{ secrets.EC2_KEY }}
          EC2_HOST: ${{ secrets.EC2_HOST }}


      - name: Install dependencies & build
        run: |
          npm install
          npm run build

      - name: Copy frontend to EC2
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          port: 22
          source: ".next,public,package.json,package-lock.json"
          target: "/home/${{ secrets.EC2_USER }}/apps/web"

      - name: Restart frontend on EC2
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          port: 22
          script: |
            cd ~/apps/web
            npm install --production
            pm2 restart web || pm2 start npm --name "web" -- start
            pm2 save
